AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DatabaseUrl:
    Type: String
    Description: NeonDB connection string
    NoEcho: true

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs20.x

Resources:
  AwsNerdearlaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          CRIPTOYA_API_BASE_URL: https://criptoya.com/api

  FxRatesApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: api.handler
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
      Events:
        GetFxRates:
          Type: Api
          Properties:
            Path: /fx-rates
            Method: GET

Outputs:
  AwsNerdearlaFunction:
    Description: "AWS Nerdearla Lambda Function ARN"
    Value: !GetAtt AwsNerdearlaFunction.Arn
  FxRatesApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/fx-rates"